// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import Navbar from "./components/Navbar";
//import Footer from "./components/Footer";
import { ToastProvider } from "@/Components/toast";
import { AuthProvider } from "@/contexts/AuthContext";
import ChatButtonWrapper from "@/Components/chat/ChatButtonWrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <AuthProvider>
          <ToastProvider>
            <main>{children}</main>

            {/* Floating Chat Button */}
            <ChatButtonWrapper />
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
